name: Lint
on: [push]
jobs:
  eslint:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
     - name: npm install
        run: |
          make install
        env:
          CI: true
      - name: Linter
        run: |
          make lint